Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> year=int(input("enter a year:"))
enter a year:2004
>>> if(year %400==0)or (year %4==0 and year %100 !=0):
...     print("leap year")
... else:
...     print("not a leap year")
... 
...     
leap year
>>> import math
>>> print("value of PI =",math.pi)
value of PI = 3.141592653589793
>>> PI=3.14
>>> print("constant value of PI=",PI)
constant value of PI= 3.14
