Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> print ("HELLO, welcome to python programmimg")
HELLO, welcome to python programmimg
>>> a=int(input ("enter first number:"))
enter first number:30
>>> b=int(input("enter second number:"))
enter second number:40
>>> sum=a+b
>>> print("sum=",sum)
sum= 70
>>> num=int(input("enter a number:"))
enter a number:60
>>> if num%2==0:
...     print("the number is even")
... else:
...     print("the number is odd")
... 
...     
the number is even
