Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> num = int (input ("enter a number :"))
enter a number :25
>>> square=num*num
>>> print ("square =",square)
square = 625
>>> radius=float(input("enter radius :"))
enter radius :40
>>> area=3.14*radius*radius
>>> print ("area of circle=",area)
area of circle= 5024.0
>>> value=input("enter any value:")
enter any value:30
>>> print("data type is :",type(value))
data type is : <class 'str'>
