# BASIC DEFAULT ARGUMENT 
def greet (name , msg="GOOD MORNING"):
    print("HELLO" , name+" , " ,msg)
greet("HIYA")
greet("VEDA" , "GOOD MORNING")

# POWER FUNCTION 
def power (num , exp=2):
    return num**emp
    print(power(3))
    print(power(3,3))
    print(power(2,4))
    
# MULTIPLE DEFAULT ARGUMENT 
def student_info(name , age=18 , course="B.SC.IT"):
    print("name:" , name)
    print("age:", age)
    print("course:" , course)
student_info("HIYA")
student_info("VEDA,20")
student_info("TANMAY" , 19 , "B.SC.IT")

