Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # RELATIONAL OPERATOR
>>> P=10
>>> Q=5
>>> print(P>Q)
True
>>> (P==Q)
False
>>> # LOGICAL OPERATOR
>>> x=True
>>> y=False
>>> print(x & y)
False
>>> print(x or y)
True
>>> print(not x)
False
>>> # BOOLEAN OPERATOR
>>> is_pass = True
>>> print(is_pass)
True
