Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # BITWISE OPERATOR
>>> a=5
>>> b=3
>>> print(a & b)
1
>>> print(a|b)
7
>>> # MEMBERSHIP OPERATOR
>>> numbers=[1,2,3,4]
>>> print(2 in numbers)
True
>>> print(5 not in numbers)
True
>>> # IDENTITY OPERATORS
>>> x=10
>>> y=10
>>> print(x is y)
True
>>> print(x is not y)
False
