# BASIC POSITIONAL ARGUMENT
def add(a,b):
    print("a=",a)
    print("b=",b)
    return a+b
result=add(2,5)
print("sum:",result)

#STUIDENT INFORMATION
def student_info(name , roll , marks):
    print("name:",name)
    print("roll.no:" , roll)
    print("marks:" , marks)
student_info("RAVI" , 101 ,85)

#SIMPLE INTEREST 
def simple interest (p,r,n)
    si=(p*r*n)/100
    print("simple interest :",si)
simple_interest (10000,2,2)
simple_interest(50000,1,2,3)

