Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> print("welcome to python programming!")
welcome to python programming!
>>> s=input("enter a string:")
enter a string:2045
>>> print("first character=",s[0])
first character= 2
>>> s=input("enter a string:")
enter a string:3452
>>> print("last character =",s[-1])
last character = 2
