Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> p=float(input("enter principle:"))
enter principle:2.30
>>> r=float(input("enter rate:"))
enter rate:30
>>> t=float(input("enter time :"))
enter time :40
>>> si=(p*r*t)/100
>>> print("simple interest=",si)
simple interest= 27.6
>>> a=int(input("enter first number:"))
enter first number:20
>>> b=int(input("enter second number:"))
enter second number:40
>>> if a>b:
...     print("maximum is",a)
... else:
...     print("maximum is ",b)
... 
...     
maximum is  40
