Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> a=int(input("enter first number:"))
enter first number:50
>>> b=int(input("enter second number:"))
enter second number:60
>>> c=int(input("enter third number:"))
enter third number:90
>>> print("sum=",a+b+c)
sum= 200
>>> name=input("enter your name :")
enter your name :DIYA
>>> print("HELLO",name)
HELLO DIYA
